[15:39:46.605] Running build in Washington, D.C., USA (East) – iad1
[15:39:46.614] Build machine configuration: 2 cores, 8 GB
[15:39:46.659] Cloning github.com/diego00711/inksa-restaurantes (Branch: main, Commit: 00d7b57)
[15:39:50.347] Cloning completed: 3.688s
[15:39:53.102] Restored build cache from previous deployment (CcHToUZa625dKsEVt8UUYmhAkWQ5)
[15:39:55.453] Running "vercel build"
[15:39:55.877] Vercel CLI 44.2.10
[15:39:56.537] Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
[15:39:56.538] Using pnpm@10.x based on project creation date
[15:39:56.538] To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
[15:39:56.539] Running "install" command: `pnpm install --no-frozen-lockfile`...
[15:39:57.378] Progress: resolved 1, reused 0, downloaded 0, added 0
[15:39:58.380] Progress: resolved 44, reused 0, downloaded 41, added 0
[15:39:59.404] Progress: resolved 81, reused 0, downloaded 70, added 0
[15:40:00.404] Progress: resolved 186, reused 0, downloaded 162, added 0
[15:40:01.419] Progress: resolved 302, reused 0, downloaded 241, added 0
[15:40:02.020] Already up to date
[15:40:02.072] Progress: resolved 376, reused 0, downloaded 314, added 0, done
[15:40:02.495]  WARN  Issues with peer dependencies found
[15:40:02.496] .
[15:40:02.496] └─┬ react-day-picker 8.10.1
[15:40:02.496]   ├── ✕ unmet peer date-fns@"^2.28.0 || ^3.0.0": found 4.1.0
[15:40:02.496]   └── ✕ unmet peer react@"^16.8.0 || ^17.0.0 || ^18.0.0": found 19.1.0
[15:40:02.496] 
[15:40:02.502] Done in 5.9s using pnpm v10.12.4
[15:40:02.622] Running "pnpm run build"
[15:40:02.991] 
[15:40:02.992] > inksa-restaurantes@0.0.0 build /vercel/path0/inksa-restaurantes
[15:40:02.992] > vite build
[15:40:02.992] 
[15:40:03.286] [36mvite v6.3.5 [32mbuilding for production...[36m[39m
[15:40:03.357] transforming...
[15:40:03.388] [32m✓[39m 4 modules transformed.
[15:40:03.390] [31m✗[39m Build failed in 77ms
[15:40:03.391] [31merror during build:
[15:40:03.391] [31m[vite:esbuild] Transform failed with 1 error:
[15:40:03.391] /vercel/path0/inksa-restaurantes/src/App.jsx:196:0: ERROR: Unexpected end of file[31m
[15:40:03.391] file: [36m/vercel/path0/inksa-restaurantes/src/App.jsx:196:0[31m
[15:40:03.391] [33m
[15:40:03.391] [33mUnexpected end of file[33m
[15:40:03.391] 194|            </TabsList>
[15:40:03.391] 195|            <TabsContent value="dashboard" className="space-y-6 mt-4"><StatsCards /><ChartsSection /><Card><CardHeader><CardTitle>Pedidos Recentes</CardTitle></CardHeader><CardContent><div className="grid md:grid-cols-2 lg:grid-c
[15:40:03.391] 196|  
[15:40:03.391]    |  ^
[15:40:03.392] [31m
[15:40:03.392]     at failureErrorWithLog (/vercel/path0/inksa-restaurantes/node_modules/.pnpm/esbuild@0.25.5/node_modules/esbuild/lib/main.js:1463:15)
[15:40:03.392]     at /vercel/path0/inksa-restaurantes/node_modules/.pnpm/esbuild@0.25.5/node_modules/esbuild/lib/main.js:734:50
[15:40:03.392]     at responseCallbacks.<computed> (/vercel/path0/inksa-restaurantes/node_modules/.pnpm/esbuild@0.25.5/node_modules/esbuild/lib/main.js:601:9)
[15:40:03.392]     at handleIncomingPacket (/vercel/path0/inksa-restaurantes/node_modules/.pnpm/esbuild@0.25.5/node_modules/esbuild/lib/main.js:656:12)
[15:40:03.392]     at Socket.readFromStdout (/vercel/path0/inksa-restaurantes/node_modules/.pnpm/esbuild@0.25.5/node_modules/esbuild/lib/main.js:579:7)
[15:40:03.392]     at Socket.emit (node:events:524:28)
[15:40:03.392]     at addChunk (node:internal/streams/readable:561:12)
[15:40:03.392]     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
[15:40:03.392]     at Readable.push (node:internal/streams/readable:392:5)
[15:40:03.392]     at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)[39m
[15:40:03.413]  ELIFECYCLE  Command failed with exit code 1.
[15:40:03.427] Error: Command "pnpm run build" exited with 1
[15:40:03.953] 
[15:40:06.831] Exiting build container
